console.log("Hello World");
// console.log(a);
//js...........
console.log("Not able to do work today :( really sad with myself ")
console.log("Need major changes")
console.log("Need major changes")

console.log("xyz")
console.log("xyz")

console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")


console.log("xyz")
console.log("xyz")


console.log("xyz")
console.log("xyz")
console.log("xyz")


console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")


console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")

console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("xyz")
console.log("hi")
console.log("xyz")
console.log("xyz")
console.log("hi")
console.log("hi")
console.log("xyz")
console.log("xyz")
console.log("hi")